### ISSUE TITLE
Protection of device

### ISSUE THREAD

**Issue by LaurensVanAcker** [krisbuist/timeular-zei-linux#4]
Hi

They now made the API and Toggle sync a payed service (EUR 9). I see your code is made in Go, so I should be able to adapt is so it can run on my Mac and then directly report to Toggle? I'm I correct that the hardware device itself is completely unencrypted? So you can read out the position from the device itself without (now payed) API?

**Comment by pauldub** [comment]
Yes you can read the position over bluetooth without the API, this gives you an integer indicating which side the device is sitting on.

**Comment by krisbuist** [comment]
Yes, that's correct. There is no encryption over this Bluetooth protocol, the Go application just reads your defined activities from the Timeular API and the current active side of your Zei device.

With some programming it would definitely be possible to connect the application straight to the Toggl API instead of via the Timeular integration :)
